### ISSUE TITLE
Base de datos de la biblia en versión español y catolica.

### ISSUE THREAD

**Issue by mamuts1532** [stonarelli/bibliar#3]
Hola   @stonarelli espero todo este bien por su lado, estoy pensando en un proyecto personal y sin animo de lucho. Para esto necesito una base de datos de la biblia en español (versión catolica), su proyeco me parece interesante aunque la verdad no lo entiendo muy bien.

Le agradesco si me puede ayudar con cualquier información que me pueda ayudar a encontrar la base de datos que necesito.

Muchas gracias por su ayuda.  

Atentamente:

Jorge Guevara.

**Comment by stonarelli** [comment]
Hola! El proyecto funciona si insertas en una base de datos todas las traducciones de la Biblia que encuentras en la carpeta SQL. Luego modificas el archivo api.php con los datos de conexion a la base de datos.

Si solo buscas la traducccion al espanol, entonces este es el archivp sql para insertar en tu base de datos:

https://github.com/stonarelli/bibliar/blob/master/sql/rv60.sql
