### ISSUE TITLE
Consulta sobre  proyectos relacionados con la Biblia

### ISSUE THREAD

**Issue by alxandev** [stonarelli/bibliar#4]
Hola buenas tardes
Dios te bendiga 
@stonarelli, cómo estás?.

@stonarelli te escribo con respecto para involucrarme con proyectos en lo referente a la biblia. 

Soy cristiano evangélico y gracias a Dios, soy programador analista, me dedico a desarrollar páginas web y aplicaciones web para ministerios e iglesias cristianos. 

Trabajo con los lenguajes de programación php y python bien sea aplicaciones web o de tipo escritorio para Windows y Gnu Linux. 

Estoy a tu orden para trabajar en cualquier proyecto que esté relacionado con la biblia. 

Alexander Nava

**Comment by stonarelli** [comment]
Hola Alexander,

Por el momento no tengo ningun proyecto relacionado con la Biblia.

De tenerlo sin dudas que te voy a contactar!

Gracias!
